import type { Alert, DemoState, Truck } from "./types";
import { hoursAgo, minutesAgo } from "./ids";

export const DEMO_FLEET = "Heartland Freight";
export const DEMO_REGION = "Midwest regional · 24 trucks in this demo";

const trucks: Truck[] = [
  { id: "t-101", unit: "HF-101", vin: "1HSDJAPR8NN123101", year: 2022, make: "Freightliner", model: "Cascadia", type: "dry_van", driver: "Marcus Hale", location: "I-80, Iowa City, IA", status: "en_route", miles: 412_880 },
  { id: "t-104", unit: "HF-104", vin: "3AKJHHDR8NSDL4104", year: 2021, make: "Kenworth", model: "T680", type: "reefer", driver: "Priya Shah", location: "Kansas City yard", status: "available", miles: 487_210 },
  { id: "t-107", unit: "HF-107", vin: "1XKYDP9X5NJ107331", year: 2023, make: "Peterbilt", model: "579", type: "dry_van", driver: "Andre Cole", location: "I-35, Des Moines, IA", status: "en_route", miles: 198_440 },
  { id: "t-109", unit: "HF-109", vin: "1FUJHHDR8NLKH2109", year: 2020, make: "Freightliner", model: "Cascadia", type: "flatbed", driver: "Elena Ruiz", location: "Omaha shop lane", status: "available", miles: 623_105 },
  { id: "t-112", unit: "HF-112", vin: "4V4NC9EH8NN112908", year: 2022, make: "Volvo", model: "VNL 760", type: "reefer", driver: "James Okonkwo", location: "I-55, Springfield, IL", status: "en_route", miles: 301_772 },
  { id: "t-115", unit: "HF-115", vin: "1XPBDP9X8ND115220", year: 2019, make: "Peterbilt", model: "579", type: "dry_van", driver: "Kelly Nguyen", location: "St. Louis drop lot", status: "available", miles: 701_334 },
  { id: "t-118", unit: "HF-118", vin: "3HSDZAPR5NN118441", year: 2023, make: "International", model: "LT", type: "dry_van", driver: "Chris Patton", location: "I-74, Peoria, IL", status: "en_route", miles: 154_980 },
  { id: "t-120", unit: "HF-120", vin: "1M1AN07Y8NM120773", year: 2021, make: "Mack", model: "Anthem", type: "flatbed", driver: "Sofia Alvarez", location: "Indianapolis yard", status: "available", miles: 388_201 },
  { id: "t-122", unit: "HF-122", vin: "1HSDJAPR7NN122019", year: 2022, make: "Freightliner", model: "Cascadia", type: "reefer", driver: "Ben Walker", location: "I-29, St. Joseph, MO", status: "en_route", miles: 276_540 },
  { id: "t-125", unit: "HF-125", vin: "4V4NC9TJ8NN125662", year: 2020, make: "Volvo", model: "VNL 760", type: "dry_van", driver: "Nina Patel", location: "Chicago south staging", status: "available", miles: 544_890 },
  { id: "t-128", unit: "HF-128", vin: "1XKYDP9X8NJ128104", year: 2023, make: "Kenworth", model: "T680", type: "reefer", driver: "Omar Haddad", location: "I-70, Columbia, MO", status: "en_route", miles: 167_220 },
  { id: "t-130", unit: "HF-130", vin: "3AKJGLD56ESJL2130", year: 2018, make: "Freightliner", model: "Cascadia", type: "dry_van", driver: "Rita Gomez", location: "Lincoln, NE yard", status: "available", miles: 812_440 },
  { id: "t-133", unit: "HF-133", vin: "1FUJHHDR5NL133881", year: 2021, make: "Freightliner", model: "Cascadia", type: "flatbed", driver: "Tyler Brooks", location: "I-80, Grand Island, NE", status: "en_route", miles: 429_110 },
  { id: "t-136", unit: "HF-136", vin: "1XPBDP9X5ND136447", year: 2022, make: "Peterbilt", model: "579", type: "dry_van", driver: "Aisha Rahman", location: "Cedar Rapids shop", status: "available", miles: 248_660 },
  { id: "t-139", unit: "HF-139", vin: "4V4NC9EH5NN139902", year: 2023, make: "Volvo", model: "VNL 860", type: "reefer", driver: "Dan Cho", location: "I-94, Kenosha, WI", status: "en_route", miles: 121_305 },
  { id: "t-141", unit: "HF-141", vin: "1HSDJAPR2NN141550", year: 2020, make: "International", model: "LT", type: "dry_van", driver: "Heather Quinn", location: "Davenport yard", status: "available", miles: 590_778 },
  { id: "t-144", unit: "HF-144", vin: "3HSDZAPR8NN144218", year: 2022, make: "Freightliner", model: "Cascadia", type: "reefer", driver: "Luis Ortega", location: "I-35, Wichita, KS", status: "en_route", miles: 333_019 },
  { id: "t-147", unit: "HF-147", vin: "1XKYDP9X2NJ147773", year: 2019, make: "Kenworth", model: "T680", type: "flatbed", driver: "Megan Price", location: "Topeka shop", status: "available", miles: 678_441 },
  { id: "t-150", unit: "HF-150", vin: "1M1AN07Y2NM150991", year: 2021, make: "Mack", model: "Anthem", type: "dry_van", driver: "Jon Park", location: "I-57, Champaign, IL", status: "en_route", miles: 364_220 },
  { id: "t-152", unit: "HF-152", vin: "4V4NC9TJ2NN152084", year: 2023, make: "Volvo", model: "VNL 760", type: "reefer", driver: "Carla Mendes", location: "Milwaukee drop", status: "available", miles: 98_540 },
  { id: "t-155", unit: "HF-155", vin: "1FUJHHDR8NL155330", year: 2020, make: "Freightliner", model: "Cascadia", type: "dry_van", driver: "Nate Simmons", location: "I-64, Evansville, IN", status: "en_route", miles: 511_870 },
  { id: "t-158", unit: "HF-158", vin: "1XPBDP9X8ND158661", year: 2022, make: "Peterbilt", model: "579", type: "flatbed", driver: "Grace Kim", location: "Sioux Falls yard", status: "available", miles: 287_993 },
  { id: "t-161", unit: "HF-161", vin: "3AKJHHDR5NSDL4161", year: 2021, make: "Kenworth", model: "T680", type: "reefer", driver: "Paul Jensen", location: "I-29, Sioux City, IA", status: "en_route", miles: 402_118 },
  { id: "t-164", unit: "HF-164", vin: "1HSDJAPR5NN164772", year: 2019, make: "International", model: "LT", type: "dry_van", driver: "Amber Cole", location: "Kansas City shop", status: "available", miles: 734_550 },
];

function alerts(now: number): Alert[] {
  return [
    {
      id: "a-01",
      truckId: "t-101",
      code: "OIL_DUE",
      title: "Oil change window opened",
      detail: "PM oil interval reached at 412,880 mi. Filter kit on the shelf at Iowa City partner shop.",
      category: "maintenance",
      severity: "routine",
      source: "Samsara",
      createdAt: hoursAgo(6.4, now),
      status: "open",
    },
    {
      id: "a-02",
      truckId: "t-104",
      code: "REEFER_TEMP",
      title: "Reefer setpoint drift",
      detail: "Box temp 4°F above setpoint for 22 minutes during pre-trip. Load is dairy, not yet dispatched.",
      category: "maintenance",
      severity: "urgent",
      source: "Geotab",
      createdAt: hoursAgo(1.8, now),
      status: "open",
    },
    {
      id: "a-03",
      truckId: "t-107",
      code: "BRAKE_FAULT",
      title: "ABS / brake circuit fault",
      detail: "Tractor ABS lamp + low air warning on I-35 southbound. Driver reports longer pedal travel.",
      category: "safety",
      severity: "critical",
      source: "Samsara",
      createdAt: minutesAgo(38, now),
      status: "open",
    },
    {
      id: "a-04",
      truckId: "t-109",
      code: "TIRE_PSI",
      title: "Drive tire pressure low",
      detail: "Outer drive 86 PSI (target 110). No temperature spike. Unit is at Omaha yard.",
      category: "maintenance",
      severity: "routine",
      source: "Samsara",
      createdAt: hoursAgo(9.1, now),
      status: "open",
    },
    {
      id: "a-05",
      truckId: "t-112",
      code: "DPF_REGEN",
      title: "DPF regen overdue",
      detail: "Parked regen requested. Soot load high. Truck can complete current run to Springfield shop.",
      category: "maintenance",
      severity: "urgent",
      source: "Geotab",
      createdAt: hoursAgo(3.2, now),
      status: "open",
    },
    {
      id: "a-06",
      truckId: "t-118",
      code: "COOLANT_LOW",
      title: "Coolant level low",
      detail: "Reservoir below add mark. Engine temp still normal. No white smoke reported.",
      category: "maintenance",
      severity: "routine",
      source: "Samsara",
      createdAt: hoursAgo(4.7, now),
      status: "open",
    },
    {
      id: "a-07",
      truckId: "t-122",
      code: "OVERHEAT",
      title: "Engine coolant over-temp",
      detail: "Coolant 221°F climbing on I-29. Derate likely. Reefer load of produce on board.",
      category: "safety",
      severity: "critical",
      source: "Samsara",
      createdAt: minutesAgo(16, now),
      status: "open",
    },
    {
      id: "a-08",
      truckId: "t-125",
      code: "INSPECT_DUE",
      title: "90-day inspection due",
      detail: "Periodic inspection expires in 3 days. Chicago south lane has an open bay tomorrow 07:00.",
      category: "compliance",
      severity: "routine",
      source: "Shop",
      createdAt: hoursAgo(11.0, now),
      status: "open",
    },
    {
      id: "a-09",
      truckId: "t-128",
      code: "AIR_LEAK",
      title: "Primary air leak suspected",
      detail: "Compressor cycling every 48s at idle. Audible leak near gladhands. Rolling on I-70.",
      category: "safety",
      severity: "critical",
      source: "Geotab",
      createdAt: minutesAgo(27, now),
      status: "open",
    },
    {
      id: "a-10",
      truckId: "t-130",
      code: "FUEL_FILTER",
      title: "Fuel filter restriction",
      detail: "Restriction sensor in yellow. No power loss yet. Unit sitting at Lincoln yard.",
      category: "maintenance",
      severity: "routine",
      source: "Samsara",
      createdAt: hoursAgo(7.5, now),
      status: "open",
    },
    {
      id: "a-11",
      truckId: "t-133",
      code: "HOS_CRIT",
      title: "HOS limit in 18 minutes",
      detail: "Driver at 10h 42m driving. Next safe haven is Grand Island, 11 miles. Load is steel coil.",
      category: "compliance",
      severity: "critical",
      source: "ELD",
      createdAt: minutesAgo(9, now),
      status: "open",
    },
    {
      id: "a-12",
      truckId: "t-136",
      code: "WIPER_PM",
      title: "Wiper / light PM due",
      detail: "Cab PM checklist: wipers streaking, marker lamp out. Truck is already at Cedar Rapids shop.",
      category: "maintenance",
      severity: "routine",
      source: "Shop",
      createdAt: hoursAgo(2.4, now),
      status: "open",
    },
    {
      id: "a-13",
      truckId: "t-139",
      code: "DEF_QUALITY",
      title: "DEF quality warning",
      detail: "DEF quality below threshold. Inducement timer started (8 hours). Reefer heading to Kenosha.",
      category: "maintenance",
      severity: "urgent",
      source: "Samsara",
      createdAt: hoursAgo(1.1, now),
      status: "open",
    },
    {
      id: "a-14",
      truckId: "t-144",
      code: "COLLISION",
      title: "Forward collision event",
      detail: "Hard brake + FCW at 62 mph. No airbag. Driver says car cut in. Dashcam clip pending review.",
      category: "safety",
      severity: "critical",
      source: "Samsara",
      createdAt: minutesAgo(21, now),
      status: "open",
    },
    {
      id: "a-15",
      truckId: "t-147",
      code: "FIFTH_WEAR",
      title: "Fifth-wheel lube / wear",
      detail: "Shop note: jaw play at last hook. Unit is parked in Topeka. Next load tomorrow 05:30.",
      category: "maintenance",
      severity: "routine",
      source: "Shop",
      createdAt: hoursAgo(8.2, now),
      status: "open",
    },
    {
      id: "a-16",
      truckId: "t-150",
      code: "IDLE_HIGH",
      title: "Excess idle this shift",
      detail: "78 minutes idle at shipper. Policy is notify driver + log; no shop work required.",
      category: "telematics",
      severity: "routine",
      source: "Geotab",
      createdAt: hoursAgo(5.0, now),
      status: "open",
    },
    {
      id: "a-17",
      truckId: "t-155",
      code: "BELT_SQUEAL",
      title: "Accessory belt noise",
      detail: "Driver reports squeal on cold start. Voltage and temps normal. Can wait for next PM window.",
      category: "maintenance",
      severity: "routine",
      source: "Samsara",
      createdAt: hoursAgo(3.8, now),
      status: "open",
    },
    {
      id: "a-18",
      truckId: "t-161",
      code: "REEFER_HOURS",
      title: "Reefer engine hours PM",
      detail: "Carrier unit at 2,980 hours. Oil/filter service due before next long haul.",
      category: "maintenance",
      severity: "routine",
      source: "Geotab",
      createdAt: hoursAgo(6.9, now),
      status: "open",
    },
    {
      id: "a-19",
      truckId: "t-164",
      code: "BRAKE_LINING",
      title: "Brake lining wear sensor",
      detail: "Steer axle lining at 22%. Not a fault lamp. Schedule before next 2,000 miles.",
      category: "maintenance",
      severity: "urgent",
      source: "Samsara",
      createdAt: hoursAgo(2.1, now),
      status: "open",
    },
    {
      id: "a-20",
      truckId: "t-120",
      code: "DOT_LIGHT",
      title: "DOT lamp out",
      detail: "Left rear marker lamp out at Indianapolis yard. Easy yard fix before dispatch.",
      category: "compliance",
      severity: "routine",
      source: "Shop",
      createdAt: hoursAgo(4.1, now),
      status: "open",
    },
  ];
}

export function createSeedState(now = Date.now()): DemoState {
  return {
    trucks: trucks.map((truck) => ({ ...truck })),
    alerts: alerts(now),
    decisions: [],
    workOrders: [],
    notifications: [],
    escalations: [],
    audit: [
      {
        id: "aud-seed",
        at: new Date(now).toISOString(),
        actor: "human",
        type: "demo.reset",
        message: `${DEMO_FLEET} demo loaded — 24 trucks, 20 open alerts sitting in the feed.`,
      },
    ],
  };
}

export function truckById(trucks: Truck[], id: string) {
  return trucks.find((truck) => truck.id === id);
}
